spring:
  application:
    name: @project.artifactId@
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/payment-ticket
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
