application:
  url-path:
    host: http://localhost:8080
    application-service: /application
    status-service: /status
    route-service: /route
    payment-service: /payment-gateway

spring:
  application:
    name: @project.artifactId@
  jpa:
    properties:
      hibername:
        show_sql: true
        use_sql_comments: true
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    jpa:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
      properties:
        hibernate:
          id:
            new_generator_mappings: false
    url: jdbc:mysql://localhost:3306/paymentticket
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

logging:
  level:
    fintechband.com.ua.payment: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight([%-5level]) %cyan(%logger{10}) %msg%n'

